### ISSUE TITLE
is it still working ?

### ISSUE THREAD

**Issue by ctf0** [raymundl/file-hyperclick#1]
hi there, this package is exactly what i was looking for so thank you so much for making it ❤️ 

however am not sure if its working or not or what are the requirements for it to jump to the file.

for example i have something like
```php
return view('pages.posts.index');
```

when i try to click `index` nothing happens, even that i've set the dir correctly in the settings `/resources` & `.js, .php.blade` to extensions

so basically the above translate to `/resources/pages/posts/index.blade.php`

**Comment by raymundl** [comment]
sorry about late response. i havent used Atom for a while. you will need to check the source codes and fix it by yourself. it's not difficult, perhaps Atom API changed.
